package utils;

import jakarta.mail.*;
import jakarta.mail.internet.*;
import java.io.File;
import java.util.Properties;

public class EmailUtil {

	public static void sendEmailReport(int total, int passed, int failed, int skipped) {

		final String senderEmail = "test.automation.mansur@gmail.com";
		final String password = "tbzk cwvm krrd ozvi";

		String[] recipients = { "mansurworkplace@gmail.com", "mmjuwel@gmail.com" };

		String allureLink = "http://your-server/allure-report/index.html";

		Properties props = new Properties();
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");

		Session session = Session.getInstance(props, new Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(senderEmail, password);
			}
		});

		try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress(senderEmail));

			InternetAddress[] addressList = new InternetAddress[recipients.length];
			for (int i = 0; i < recipients.length; i++) {
				addressList[i] = new InternetAddress(recipients[i]);
			}

			message.setRecipients(Message.RecipientType.TO, addressList);

			message.setSubject("Automation Test Execution Report");


			String htmlBody = "<div style='font-family: Arial, sans-serif;'>" +

					"<h2 style='color:#2E86C1;'>Automation Test Execution Report</h2>" +

					"<p>Hello Team,<br><br>"
					+ "The automated test suite execution has been completed. Please find the summary below.</p>" +

					"<h3 style='color:#34495E;'>Execution Summary</h3>" +

					"<table border='1' cellpadding='8' cellspacing='0' style='border-collapse:collapse; text-align:center;'>"
					+ "<tr style='background-color:#f2f2f2; font-weight:bold;'>" + "<th>Total Tests</th>"
					+ "<th>Passed</th>" + "<th>Failed</th>" + "<th>Skipped</th>" + "</tr>" +

					"<tr>" + "<td>" + total + "</td>" + "<td style='color:green; font-weight:bold;'>" + passed + "</td>"
					+ "<td style='color:red; font-weight:bold;'>" + failed + "</td>"
					+ "<td style='color:#E67E22; font-weight:bold;'>" + skipped + "</td>" + "</tr>" + "</table>" +

					"<br>" +

					"<p><b>Detailed Report:</b></p>" +

					"<a href='" + allureLink + "' "
					+ "style='display:inline-block; padding:10px 15px; background-color:#2E86C1; color:white; text-decoration:none; border-radius:5px;'>"
					+ "View Allure Report</a>" +

					"<br><br>" +

					"<p> TestNG HTML report is attached with this email for further analysis.</p>" +

					"<br>" +

					"<p style='color:gray; font-size:12px;'>"
					+ "This is an automated email generated by the Automation Test Framework." + "</p>" +

					"<br>" +

					"<p>Best Regards,<br>" + "<b>Automation QA Team</b></p>" +

					"</div>";

			MimeBodyPart messageBodyPart = new MimeBodyPart();
			messageBodyPart.setContent(htmlBody, "text/html");

			/*
			 * MimeBodyPart attachmentPart = new MimeBodyPart();
			 * attachmentPart.attachFile(new
			 * File("target/surefire-reports/emailable-report.html"));
			 */

			Multipart multipart = new MimeMultipart();
			multipart.addBodyPart(messageBodyPart);
			// multipart.addBodyPart(attachmentPart);

			message.setContent(multipart);

			Transport.send(message);

			System.out.println("Report email sent successfully!");

		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}